### ISSUE TITLE
Runtime error Warning: Use of undefined constant WPCF7_VERSION with PHP 7.3.21

### ISSUE THREAD

**Issue by quartelh** [lordofcode/wordpress.plugin.contactform7.maxmessages#1]
Hi 
I tried to use your plugin on a local WAMp having PHP 7.3.21.
After setup and testing the form I got an error 'Warning: Use of undefined constant WPCF7_VERSION' pointin to line 111.

I fixed it locally by changing in 111 and line 112 to:
```
        if (class_exists('WPCF7_ContactForm') == false) return false;
        if (class_exists('Flamingo_Inbound_Message') == false) return false;
```

Best regards, 
Herbert

**Comment by lordofcode** [comment]
Thanx Herbert, you provided the right fix. I updated the source.
